/* Campaign progression, chapter-local saves and reusable accessible puzzle controllers. */
'use strict';
(() => {
  const KEY='silent-ward-campaign-v3', clone=v=>JSON.parse(JSON.stringify(v));
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const originalStages=STAGES.map(v=>({...v}));
  const hospital={id:'hospital',name:'静默病院',en:'THE SILENT WARD',minutes:12,color:'#a3bba4',tag:'一份从未结案的午夜记录',desc:'23:48。电话又响了。五个房间，三份被抹去的证词。在午夜之前，找到离开的理由。',rooms:['station','ward','archive','power','exit'].map(id=>({id,name:ROOMS[id].name})),ending:'你在最后一扇门关上前离开了病院。但还有证词没有重见天日。',truth:'你带出了三份证词，也带出了那些被抹去的姓名。门外停着一列没有终点的列车；它的车票上，印着与你相同的档案编号。',fail:'零点。门锁落下，广播开始重复你的名字。护士站又多了一份没有结尾的值班记录。'};
  const chapters=[hospital,...CAMPAIGN_DATA], byId=Object.fromEntries(chapters.map(c=>[c.id,c]));
  const puzzles=new Map(), clueMap=new Map(), roomMap=new Map();
  let profile=readLocal(KEY); if(!profile||profile.version!==3||typeof profile.runs!=='object'||!profile.runs||typeof profile.records!=='object'||!profile.records)profile={version:3,selected:'hospital',runs:{},records:{}};
  let selected=byId[profile.selected]?profile.selected:'hospital', activePuzzle=null, playToken=0, importData=null;
  for(const c of CAMPAIGN_DATA)for(const r of c.rooms){
    const p=r.puzzle;p.chapter=c.id;p.index=r.index;p.reward=r.reward;p.hints=p.hints||[];p.room=r.id;puzzles.set(p.id,p);roomMap.set(r.id,{r,c});
    const hs=[];
    r.clues.forEach((n,i)=>{const id=p.id+'_clue'+i;NOTES[id]={title:n[0],text:n[1],location:r.name};clueMap.set(id,{room:r.id,evidence:false});hs.push([id,n[0],i?79:21,i?27:29]);});
    hs.push([p.id,p.title,77,69]);
    if(r.evidence){const id=p.id+'_evidence';NOTES[id]={title:r.evidence[0],text:r.evidence[1],location:r.name};clueMap.set(id,{room:r.id,evidence:true});hs.push([id,r.evidence[0],23,73]);}
    if(r.index===4)hs.push([p.id+'_exit','本章撤离门',50,80]);
    // Positions are computed from the actual authored 3D camera by the capture tool.
    // Fixed readable label positions; projected leader lines point to the actual objects.
    ROOMS[r.id]={name:r.name,en:r.en,cam:String(r.index+1).padStart(2,'0'),desc:r.mood,hotspots:hs};
    ITEM_DATA[p.id+'_item']={name:r.reward,icon:r.index===4?'paper':'key',desc:`${r.name}的机关已解除。${r.reward}已自动登记，可通往${c.rooms[Math.min(4,r.index+1)].name}。`,room:c.rooms[Math.min(4,r.index+1)].id};
  }
  const object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
  const unique=a=>[...new Set(a)];
  function cleanPuzzleValue(p,v){
    const base=initial(p), ints=(a,n,max)=>Array.isArray(a)&&a.length===n&&a.every(x=>Number.isInteger(x)&&x>=0&&x<max);
    if(!object(v))return base;
    if(p.type==='code')return {text:typeof v.text==='string'?v.text.replace(p.alphabet?/[^a-z]/gi:/[^0-9]/g,'').toUpperCase().slice(0,p.length):''};
    if(['order','memory','balance'].includes(p.type)){
      const max=p.type==='balance'?p.weights.length:p.labels.length, cap=p.type==='balance'?max:p.answer.length;
      if(!Array.isArray(v.chosen)||v.chosen.length>cap||!v.chosen.every(x=>Number.isInteger(x)&&x>=0&&x<max)||p.type!=='memory'&&unique(v.chosen).length!==v.chosen.length)return base;
      return {chosen:[...v.chosen]};
    }
    if(p.type==='route'){
      const a=v.path;if(!Array.isArray(a)||!a.length||a.length>p.size*p.size||a[0]!==p.answer[0]||unique(a).length!==a.length||!a.every((x,i)=>Number.isInteger(x)&&x>=0&&x<p.size*p.size&&(i===0||Math.abs(x%p.size-a[i-1]%p.size)+Math.abs(Math.floor(x/p.size)-Math.floor(a[i-1]/p.size))===1)))return base;
      return {path:[...a]};
    }
    if(p.type==='lights')return ints(v.values,p.size*p.size,2)?{values:[...v.values]}:base;
    if(p.type==='linked')return ints(v.values,3,p.mod)?{values:[...v.values]}:base;
    if(p.type==='dials'||p.type==='mix')return Array.isArray(v.values)&&v.values.length===p.labels.length&&v.values.every((x,i)=>Number.isInteger(x)&&x>=0&&x<p.values[i].length)?{values:[...v.values]}:base;
    return base;
  }
  function validRun(v,c){
    if(!object(v)||v.version!==1||!['explore','challenge'].includes(v.mode)||!c.rooms.some(r=>r.id===v.room)||!object(v.solved)||!Array.isArray(v.inventory)||!Array.isArray(v.notes)||!Array.isArray(v.evidence)||!Number.isFinite(v.remaining)||!Number.isFinite(v.elapsed))return null;
    v=clone(v);v.chapter=c.id;
    const ownNote=id=>typeof id==='string'&&NOTES[id]&&(c.id==='hospital'?!id.startsWith('cx_'):id.startsWith('cx_'+c.id+'_'));
    const ownItem=id=>typeof id==='string'&&ITEM_DATA[id]&&(c.id==='hospital'?!id.startsWith('cx_'):id.startsWith('cx_'+c.id+'_'));
    const evidenceIds=c.id==='hospital'?['phone','mirror','photo']:c.rooms.filter(r=>r.evidence).map(r=>r.puzzle.id+'_evidence');
    const keys=c.id==='hospital'?['drawer','wardDoor','locker','archiveDoor','safe','fuse','power','exit']:['exit',...c.rooms.map(r=>r.puzzle.id)];
    v.inventory=unique(v.inventory.filter(ownItem));v.notes=unique(v.notes.filter(ownNote));v.evidence=unique(v.evidence.filter(id=>evidenceIds.includes(id)));v.solved=Object.fromEntries(keys.map(k=>[k,v.solved[k]===true]));
    v.remaining=Math.max(0,Math.min(Math.ceil(c.minutes*(window.DepthModel?.LEVELS[v.depth?.level]?.multiplier||1))*60,v.remaining));v.elapsed=Math.max(0,Math.min(1e9,v.elapsed));
    v.hintLevels=Object.fromEntries(Object.entries(object(v.hintLevels)?v.hintLevels:{}).filter(([k,x])=>(keys.includes(k)||k==='done')&&Number.isInteger(x)&&x>=0&&x<=3));
    const count=x=>Number.isFinite(x)?Math.max(0,Math.min(1e7,Math.floor(x))):0;v.stats={hints:count(v.stats?.hints),wrong:count(v.stats?.wrong)};
    const bank=object(v.puzzleState)?v.puzzleState:{};v.puzzleState={};if(c.id!=='hospital')for(const r of c.rooms)if(Object.hasOwn(bank,r.puzzle.id))v.puzzleState[r.puzzle.id]=cleanPuzzleValue(r.puzzle,bank[r.puzzle.id]);
    v.circuits=Array.isArray(v.circuits)&&v.circuits.length===9&&v.circuits.every(x=>Number.isInteger(x)&&x>=0&&x<4)?v.circuits:[...INITIAL_ROT];v.archiveOrder=Array.isArray(v.archiveOrder)?unique(v.archiveOrder.filter(x=>Object.hasOwn(FILES,x))).slice(0,4):[];
    return v;
  }
  for(const c of chapters){const v=validRun(profile.runs[c.id],c);if(v)profile.runs[c.id]=v;else delete profile.runs[c.id];if(!profile.records[c.id]||typeof profile.records[c.id]!=='object')delete profile.records[c.id];}
  // Import the previous edition's active hospital run without deleting its original key.
  const legacy=validRun(saved,byId[saved?.chapter||'hospital']||hospital);if(!profile.migratedV2&&legacy&&!profile.runs[legacy.chapter]&&!profile.records[legacy.chapter]?.clears)profile.runs[legacy.chapter]=legacy;profile.migratedV2=true;
  function current(){return byId[phase==='playing'||phase==='ending'?state?.chapter||selected:selected]||hospital;}
  function roomIds(){return current().rooms.map(r=>r.id);}
  function activate(id){selected=id;profile.selected=id;const c=byId[id];STAGES.splice(0,STAGES.length,...(id==='hospital'?originalStages:c.rooms.map(r=>({key:r.puzzle.id,title:r.puzzle.title,desc:`前往${r.name}，${r.index? '利用记录解除当前联锁。':'检查两份记录并启动第一道机关。'}`,hints:r.puzzle.hints}))));}
  function persist(){writeLocal(KEY,profile);}
  function prepare(resume){if(resume&&saved?.chapter)activate(saved.chapter);else activate(selected);}
  function initial(p){switch(p.type){case 'code':return {text:''};case 'order':case 'memory':return {chosen:[]};case 'balance':return {chosen:[]};case 'dials':case 'mix':return {values:p.labels.map(()=>0)};case 'linked':return {values:[0,0,0]};case 'route':return {path:[p.answer[0]]};case 'lights':{const v=Array(p.size*p.size).fill(0);for(const i of p.presses)flip(v,i,p.size);return {values:v};}default:throw Error('Unknown puzzle type '+p.type);}}
  function puzzleState(p){const bank=state.puzzleState??={};let v=bank[p.id];const ref=initial(p);if(!v||Object.keys(ref).some(k=>Array.isArray(ref[k])? !Array.isArray(v[k])||v[k].some(x=>!Number.isInteger(x)||x<0):typeof v[k]!==typeof ref[k]))v=bank[p.id]=ref;return v;}
  function createState(mode){const c=byId[selected];return {version:1,chapter:c.id,mode,room:c.rooms[0].id,remaining:c.minutes*60,elapsed:0,inventory:[],notes:[],evidence:[],solved:{exit:false},puzzleState:{},circuits:[...INITIAL_ROT],archiveOrder:[],hintLevels:{},stats:{wrong:0,hints:0},warned90:false};}
  function canEnter(id){if(window.Depth?.enabled()&&!Depth.canEnter(id))return false;const entry=roomMap.get(id);if(!entry)return !id.startsWith('metro_')&&!id.startsWith('orphan_')&&!id.startsWith('abyss_')&&!id.startsWith('astro_');if(phase!=='playing')return true;const {r,c}=entry;return state.chapter===c.id&&(r.index===0||!!state.solved[c.rooms[r.index-1].puzzle.id]);}
  function locked(id){const {r,c}=roomMap.get(id);const prev=c.rooms[r.index-1];openModal('通道尚未开放',`<div class="chapter-lock">${icon('lock')}<p>需要先完成 <strong>${prev.name}</strong> 的「${prev.puzzle.title}」。<br>已开放的区域可以随时返回，证词不会消失。</p></div><button class="btn primary wide" data-action="go" data-room="${prev.id}">返回上一处区域</button>`,'INTERLOCK / 区域联锁');}
  function save(v){if(byId[v.chapter||'hospital']){profile.runs[v.chapter||'hospital']=clone(v);persist();}}
  function clearRun(){delete profile.runs[state?.chapter||selected];persist();}
  function doneStage(){return {key:'done',title:'携带证词，从撤离门离开',desc:'本章五道联锁已解除。收集三份证词后，检查最后区域的撤离门。',hints:['可以返回所有已开放区域补齐证词。','三份证词分别位于本章的第 1、第 3、第 5 区域。','前往第 5 区域，点击「本章撤离门」，再确认撤离。']};}
  function seen(id){return id.endsWith('_exit')?!!state?.solved.exit:puzzles.has(id)?!!state?.solved[id]:state?.notes.includes(id);}
  function inspect(id){
    if(phase!=='playing'||paused)return;
    const note=clueMap.get(id),p=puzzles.get(id),exit=id.endsWith('_exit')&&puzzles.get(id.slice(0,-5));
    const room=note?.room||p?.room||exit?.room;if(!room||!roomIds().includes(room)||!canEnter(room))return;
    audio.click();
    if(note){note.evidence?addEvidence(id):addNote(id);const n=NOTES[id];openModal(n.title,doc(n.title,`<p>${esc(n.text)}</p>${note.evidence?'<p class="handwritten">把它带出去。不要让记录再次消失。</p>':''}`,current().en)+noteFooter(),note.evidence?'EVIDENCE / 本章证词':'CLUE / 现场记录');if(note.evidence)scare(roomMap.get(room).r.mood);renderScene();return;}
    if(exit){if(!state.solved.exit){openModal('撤离门没有响应','<p>本章最后一道机关还没有解除。完成当前目标后再返回。</p><button class="btn primary wide" data-action="close">继续调查</button>','EXTRACTION / 尚未解锁');return;}openModal('结束本章调查',`<p>已解除全部五道机关。当前证词：<strong>${state.evidence.length} / 3</strong>。</p><p>${state.evidence.length===3?'三份证词齐全，撤离后会计入战役的完整证据。':'撤离仍能通关，但不会记录本章完整证据。现在仍可返回已开放区域寻找遗漏。'}</p><div class="btn-row"><button class="btn ghost" data-action="close">继续搜证</button><button class="btn primary" data-action="escape">确认撤离</button></div>`,'CHAPTER COMPLETE / 撤离确认');return;}
    if(state.solved[id]){showSuccess(p);return;}activePuzzle=id;renderPuzzle();
  }
  function flip(a,index,size){const x=index%size,y=Math.floor(index/size);for(const [dx,dy] of [[0,0],[-1,0],[1,0],[0,-1],[0,1]])if(x+dx>=0&&x+dx<size&&y+dy>=0&&y+dy<size)a[(y+dy)*size+x+dx]^=1;}
  const pc=(act,i,text,cls='')=>`<button type="button" class="puzzle-tile ${cls}" data-pc="${act}" data-index="${i}">${text}</button>`;
  function instruction(p){return {code:p.alphabet?'还原四个英文字母。支持大小写；可直接使用键盘或下方字母按键。':`输入 ${p.length} 位数字，保留开头的零。`,order:'依次选择卡片排入位置；点已选卡片可撤回。',memory:'播放原始序列或查阅歌词，然后依次点选图案。静音也能完成。',balance:`选择砝码，总和恰好为 ${p.target}。再次点击取消选择。`,dials:'点击旋钮循环切换档位，按记录配置后验证。',mix:'点击各量筒加一格，超过四格回到零。',linked:`每次操作同时推动两只表盘；超过 ${p.mod-1} 回到 0。`,lights:'点击翻转本格及上下左右相邻灯，让所有亮灯熄灭。',route:'从 IN 出发，只能连接上下左右相邻节点。点击上一节点撤回一步。'}[p.type];}
  function renderPuzzle(){
    const p=puzzles.get(activePuzzle);if(!p||!state)return;const v=puzzleState(p),focus=document.activeElement?.dataset.pc,fi=document.activeElement?.dataset.index;
    let body=`<div class="puzzle-meta"><span>${current().en} / ${String(p.index+1).padStart(2,'0')}</span><span>联锁 ${p.index+1} / 5</span></div><p class="puzzle-intro">${instruction(p)}</p>`;
    if(p.type==='code')body+=`<label class="code-label" for="campaignCode">${p.alphabet?'字母撤销口令':'联锁密码'}</label><input id="campaignCode" class="code-display" type="text" inputmode="${p.alphabet?'text':'numeric'}" maxlength="${p.length}" autocomplete="off" autocapitalize="characters" spellcheck="false" value="${esc(v.text)}" placeholder="${'—'.repeat(p.length)}" aria-label="${p.length}位${p.alphabet?'字母':'数字'}密码"><div class="keypad campaign-keypad ${p.alphabet?'letters':''}">${(p.alphabet?'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''):[1,2,3,4,5,6,7,8,9,'清空',0,'⌫']).map(x=>pc('digit',String(x),x)).join('')}</div>`;
    if(p.type==='order'||p.type==='memory')body+=`<div class="sequence-slots" aria-live="polite">${Array.from({length:p.answer.length},(_,i)=>pc('remove',i,`<small>0${i+1}</small><b>${v.chosen[i]===undefined?'·':p.labels[v.chosen[i]]}</b>`,v.chosen[i]!==undefined?'filled':'')).join('')}</div>${p.type==='memory'?'<div class="memory-status" id="memoryStatus" role="status">原始序列可不限次数重播</div><button type="button" class="btn ghost wide" data-pc="play">▷ 播放原始序列</button>':''}<div class="choice-bank">${p.labels.map((x,i)=>pc('choose',i,`<small>${String(i+1).padStart(2,'0')}</small><b>${x}</b>`,p.type==='order'&&v.chosen.includes(i)?'selected':'')).join('')}</div>`;
    if(p.type==='balance'){const sum=v.chosen.reduce((a,i)=>a+p.weights[i],0);body+=`<div class="balance-art"><span>所选砝码 <b>${sum}</b></span><span class="balance-beam" style="transform:rotate(${Math.max(-12,Math.min(12,(sum-p.target)*2))}deg)">⚊</span><span>目标读数 <b>${p.target}</b></span></div><div class="choice-bank">${p.labels.map((x,i)=>pc('weight',i,`<b>${x}</b><small>${v.chosen.includes(i)?'已放置':'点击放置'}</small>`,v.chosen.includes(i)?'selected':'')).join('')}</div>`;}
    if(p.type==='dials'||p.type==='mix')body+=`<div class="dial-bank ${p.type==='mix'?'liquids':''}">${p.labels.map((label,i)=>pc('dial',i,`<small>${label}</small>${p.type==='mix'?`<span class="beaker"><span style="height:${v.values[i]*23}%"></span></span>`:`<span class="dial-face" style="--turn:${v.values[i]/p.values[i].length*360}deg"><i></i>${p.visual==='rings'?'◎':p.visual==='shadow'?'✧':'◌'}</span>`}<b>${p.values[i][v.values[i]]}</b><small>点击转到下一档</small>`)).join('')}</div>`;
    if(p.type==='linked')body+=`<div class="gauge-bank">${v.values.map((x,i)=>`<div class="gauge"><span class="gauge-needle" style="transform:rotate(${x/p.mod*300-150}deg)"></span><b>${x}</b><small>${['左表','中表','右表'][i]} / 目标 ${p.target[i]}</small></div>`).join('')}</div><div class="choice-bank">${p.labels.map((x,i)=>pc('link',i,x)).join('')}</div>`;
    if(p.type==='lights')body+=`<div class="light-readout"><b>${v.values.reduce((a,b)=>a+b,0)}</b> / ${p.size*p.size} 个警报仍然亮起</div><div class="logic-grid lights-grid" style="--size:${p.size}">${v.values.map((x,i)=>`<button type="button" data-pc="light" data-index="${i}" class="light-cell ${x?'lit':''}" aria-label="第${i+1}格，${x?'亮':'灭'}" aria-pressed="${!!x}"><span></span><small>${String(i+1).padStart(2,'0')}</small></button>`).join('')}</div>`;
    if(p.type==='route'){const points=v.path.map(x=>`${(x%p.size+.5)*100/p.size},${(Math.floor(x/p.size)+.5)*100/p.size}`).join(' ');body+=`<div class="route-compass">N / 北 ↑ <span>已连接 ${v.path.length} 个节点</span></div><div class="logic-grid route-grid ${p.visual==='stars'?'stars':''}" style="--size:${p.size}"><svg class="route-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline points="${points}"/></svg>${Array.from({length:p.size*p.size},(_,i)=>pc('route',i,`<b>${i+1}</b><small>${i===p.answer[0]?'IN':i===p.answer.at(-1)?'OUT':v.path.includes(i)?'●':'·'}</small>`,v.path.includes(i)?'selected':'')).join('')}</div>`;}
    body+=`<div class="feedback campaign-feedback" id="campaignFeedback" role="status">${state.mode==='challenge'?'错误验证 −'+(window.Depth?.wrongCost()||10)+' 秒；不完整输入不会扣时。':'探索模式：可以反复尝试，不会扣时。'}</div><button class="btn primary wide" type="submit">验证当前设置 ${icon('arrow')}</button><div class="btn-row"><button type="button" class="btn small ghost" data-pc="reset">重置本机关</button><button type="button" class="btn small ghost" data-action="journal">打开线索本</button><button type="button" class="btn small ghost" data-action="hint">提示</button></div>`;
    openModal(p.title,`<form id="campaignPuzzleForm">${body}</form>`,'INTERLOCK / 现场机关',false,'campaign-puzzle');
    if(focus&&fi!==undefined)requestAnimationFrame(()=>document.querySelector(`[data-pc="${focus}"][data-index="${CSS.escape(fi)}"]`)?.focus({preventScroll:true}));
  }
  function message(text,bad=false){const e=$('#campaignFeedback');if(e){e.textContent=text;e.classList.toggle('error',bad);}}
  function same(a,b){return a.length===b.length&&a.every((x,i)=>x===b[i]);}
  function isCorrect(p,v){switch(p.type){case 'code':return v.text.toUpperCase()===p.answer;case 'order':case 'memory':return same(v.chosen,p.answer);case 'balance':return v.chosen.reduce((s,i)=>s+p.weights[i],0)===p.target;case 'dials':case 'mix':return same(v.values,p.answer);case 'linked':return same(v.values,p.target);case 'lights':return v.values.every(x=>!x);case 'route':return same(v.path,p.answer);}return false;}
  function check(){const p=puzzles.get(activePuzzle);if(!p||phase!=='playing'||paused||state.solved[p.id]||activeModal!=='campaign-puzzle')return;if(window.Depth&&!Depth.allowBase(p.id))return;const v=puzzleState(p);if(p.type==='code')v.text=$('#campaignCode').value.trim().toUpperCase();if((p.type==='code'&&v.text.length!==p.length)||(['memory','order'].includes(p.type)&&v.chosen.length!==p.answer.length)){message('请先补齐全部位置；此次不扣时。');saveGame();return;}
    if(!isCorrect(p,v)){penalty();if(phase==='playing'){message('联锁拒绝了当前设置。记录中还有一条关系没有满足。',true);saveGame();}return;}
    state.solved[p.id]=true;if(p.index===4)state.solved.exit=true;addItem(p.id+'_item');audio.chime();renderScene();saveGame();showSuccess(p);if(p.index===2)scare('装置已经安静了。你却又听见一次确认声。');}
  function showSuccess(p){const c=byId[p.chapter],next=c.rooms[p.index+1];openModal('联锁已经解除',`<div class="mechanism-cleared">${icon('check')}<small>INTERLOCK ${p.index+1} / 5 · VERIFIED</small><h3>${p.title}</h3><p>已获得：${p.reward}。</p></div><p>${next?`通往<strong>${next.name}</strong>的通道已经开放。`:'全部联锁已解除。检查撤离门离开本章；现在仍可回头收集证词。'}</p><div class="btn-row"><button class="btn ghost" data-action="close">继续检查这里</button>${next?`<button class="btn primary" data-action="go" data-room="${next.id}">前往${next.name}</button>`:`<button class="btn primary" data-action="inspect" data-id="${p.id}_exit">检查撤离门</button>`}</div>`,'PROGRESS / 通道开放');}
  async function playback(){const p=puzzles.get(activePuzzle);if(!p||p.type!=='memory')return;const token=++playToken,run=state;const wait=ms=>new Promise(r=>setTimeout(r,ms));for(let k=0;k<p.answer.length;k++){if(token!==playToken||state!==run||phase!=='playing'||paused||activeModal!=='campaign-puzzle'||activePuzzle!==p.id)return;document.querySelectorAll('[data-pc="choose"]').forEach(b=>b.classList.remove('playing'));const btn=document.querySelector(`[data-pc="choose"][data-index="${p.answer[k]}"]`);btn?.classList.add('playing');const status=$('#memoryStatus');if(status)status.textContent=`正在复现 ${k+1} / ${p.answer.length}：${p.labels[p.answer[k]]}`;if(preferences.sound)audio.tone(220+p.answer[k]*65,.45,'sine',.04);await wait(800);btn?.classList.remove('playing');await wait(180);}if(token===playToken&&$('#memoryStatus'))$('#memoryStatus').textContent='复现结束。依次点击图案，然后验证。';}
  function puzzleAction(b){if(phase!=='playing'||paused||activeModal!=='campaign-puzzle')return;const p=puzzles.get(activePuzzle),v=puzzleState(p),a=b.dataset.pc,i=Number(b.dataset.index);if(a==='play'){playback();return;}if(a==='reset'){state.puzzleState[p.id]=initial(p);playToken++;}
    else if(a==='digit'){const text=b.dataset.index;v.text=text==='清空'?'':text==='⌫'?v.text.slice(0,-1):(v.text+text).slice(0,p.length);}
    else if(a==='choose'){if(p.type==='order'&&v.chosen.includes(i))v.chosen=v.chosen.filter(x=>x!==i);else if(v.chosen.length<p.answer.length)v.chosen.push(i);}
    else if(a==='remove')v.chosen.splice(i,1);
    else if(a==='weight')v.chosen=v.chosen.includes(i)?v.chosen.filter(x=>x!==i):[...v.chosen,i];
    else if(a==='dial')v.values[i]=(v.values[i]+1)%p.values[i].length;
    else if(a==='link')v.values=v.values.map((x,j)=>(x+p.matrix[i][j])%p.mod);
    else if(a==='light')flip(v.values,i,p.size);
    else if(a==='route'){const last=v.path.at(-1);if(i===v.path.at(-2))v.path.pop();else if(!v.path.includes(i)&&Math.abs(i%p.size-last%p.size)+Math.abs(Math.floor(i/p.size)-Math.floor(last/p.size))===1)v.path.push(i);else{message('请选择相邻的未经过节点；点击上一节点可后退。');return;}}
    else return;audio.click();renderPuzzle();saveGame();
  }
  function refreshMenu(){
    const c=byId[selected];document.body.dataset.chapter=c.id;document.documentElement.style.setProperty('--chapter-accent',c.color);
    $('#chapterRail').innerHTML=chapters.map((v,i)=>{const run=profile.runs[v.id],rec=profile.records[v.id],count=run?(v.id==='hospital'?originalStages:v.rooms.map(r=>({key:r.puzzle.id}))).filter(s=>run.solved[s.key]).length:0;return `<button class="chapter-card ${v.id===selected?'active':''}" data-campaign="select" data-chapter="${v.id}" style="--card-accent:${v.color}" aria-pressed="${v.id===selected}"><span class="chapter-id">CASE / 0${i+1}</span><strong>${v.name}</strong><small>${v.minutes} MIN · 5 区域</small><span class="chapter-status">${rec?.truth?'完整证据 ✓':run?`调查中 ${count}/5`:rec?.clears?'已撤离 · 可补齐证词':i===0?'原始档案':'新增档案'}</span></button>`;}).join('');
    $('.surveillance-time').innerHTML=`23<span>:</span>${String(60-c.minutes).padStart(2,'0')}`;$('.case-tag').textContent=c.tag;$('.edition-line').textContent=`静默病院 / 档案 0${chapters.indexOf(c)+1} · THE SILENCE PROTOCOL`;
    const split=c.name.length>4?3:2;$('.cinema-menu h1').innerHTML=`${c.name.slice(0,split)}<span>${c.name.slice(split)}</span><i aria-hidden="true">${c.name}</i>`;$('.hero-subtitle').textContent=c.en;
    $('.hero-desc').innerHTML=`${c.desc}<br><strong>5 个区域 · 5 道机关 · 3 份证词 · 独立存档</strong>`;
    $('[data-mode="challenge"] span').textContent=`${c.minutes}:00 / 本章限时`; $('[data-action="start"] span').textContent=profile.records[c.id]?.clears?'重新调查本章':'进入本章';
    $('#continueBtn').hidden=!saved;$('#continueBtn').textContent='继续本章';$('.sector-heading span:first-child').textContent='本章调查区域';
    SW.app?.renderCards();SW.app?.preview(c.rooms[0].id);window.Depth?.refreshMenu();
  }
  function select(id){if(!byId[id]||phase!=='title')return;activate(id);saved=profile.runs[id]?clone(profile.runs[id]):null;persist();refreshMenu();}
  function record(escaped){const id=state.chapter||'hospital';if(!escaped)return;const old=profile.records[id]||{},truth=state.evidence.length===3;profile.records[id]={clears:(old.clears||0)+1,truth:!!old.truth||truth,evidence:Math.max(old.evidence||0,state.evidence.length),best:Math.min(old.best||Infinity,state.elapsed),wrong:state.stats.wrong,hints:state.stats.hints,lastMode:state.mode,depthClears:(old.depthClears||0)+(state.depth?1:0),nightmareClears:(old.nightmareClears||0)+(state.depth?.level==='nightmare'?1:0),bestDepth:state.depth?Math.min(old.bestDepth||Infinity,state.elapsed):(old.bestDepth||null),lastDifficulty:state.depth?.level||'classic',lastSeed:state.depth?.seed||'',lastRating:window.Depth?.rating()||''};persist();}
  function finish(escaped=true){if(escaped&&window.Depth?.blockExit())return;if(phase!=='playing'||(escaped&&!state.solved.exit))return;const c=current(),truth=escaped&&state.evidence.length===3;record(escaped);phase='ending';paused=false;closeModal(true);audio.sync();clearSave();clearTimeout(scareTimeout);$('#apparition').classList.remove('visible');$('#gameScreen').hidden=true;$('#startScreen').hidden=true;$('#endingScreen').hidden=false;const next=chapters[chapters.indexOf(c)+1];const full=chapters.every(x=>profile.records[x.id]?.truth);
    $('#endingScreen').innerHTML=`<div class="ending-card campaign-ending"><div class="ending-mark">${icon(escaped?'exit':'clock')}</div><div class="eyebrow">${!escaped?'ENDING C / RECORD INTERRUPTED':truth?'ENDING S / EVIDENCE PRESERVED':'ENDING A / EXTRACTION'} · CASE 0${chapters.indexOf(c)+1}</div><h1>${!escaped?'记录中断':truth?'证词重见天日':'撤离成功'}</h1><h2>${c.name}</h2><p>${!escaped?c.fail:truth?c.truth:c.ending}</p><div class="ending-stats"><div><b>${formatTime(state.elapsed)}</b><small>本章探索用时</small></div><div><b>${completed()} / 5</b><small>解除机关</small></div><div><b>${state.evidence.length} / 3</b><small>证词</small></div></div><p class="small">${state.mode==='challenge'?'限时挑战':'无时限探索'} · 错误 ${state.stats.wrong} 次 · 提示 ${state.stats.hints} 条</p>${window.Depth?.endingHTML(escaped)||''}${full?'<div class="campaign-true-notice">五处完整证据已齐全。总终章「让所有人记得」已解锁。</div>':''}<div class="ending-actions"><button class="btn primary" data-campaign="${full?'archive':'next'}" ${escaped&&next&&!full?`data-chapter="${next.id}"`:''}>${full?'查看总终章':escaped&&next?`下一章 · ${next.name}`:'返回章节菜单'}</button><button class="btn ghost" data-action="title">章节菜单</button><button class="btn ghost" data-action="walkthrough">本章攻略</button></div><p class="ending-footer">THE SILENCE PROTOCOL / ${chapters.filter(x=>profile.records[x.id]?.clears).length} OF 5 CASES RESOLVED</p></div>`;window.scrollTo(0,0);}
  function archive(){const n=chapters.filter(c=>profile.records[c.id]?.truth).length,clears=chapters.filter(c=>profile.records[c.id]?.clears).length,evidence=chapters.reduce((s,c)=>s+(profile.records[c.id]?.evidence||0),0);openModal('静默协议 · 战役档案',`<div class="campaign-summary"><div><b>${clears} / 5</b><span>已撤离章节</span></div><div><b>${evidence} / 15</b><span>已带出证词</span></div><div><b>${n} / 5</b><span>完整证据</span></div></div><p>五章均可独立进入。进度分别保存；只有确认撤离后，证词才会记录在战役档案中。重复通关不会降低已经取得的完整证据。</p><div class="case-files">${chapters.map((c,i)=>{const v=profile.records[c.id];return `<article><span>0${i+1} / ${c.en}</span><h3>${c.name}</h3><p>${v?.clears?`撤离 ${v.clears} 次 · 最快 ${formatTime(v.best)} · 证词 ${v.evidence}/3`:'尚未完成撤离'}</p><strong>${v?.truth?'证据链完整':'证据尚未齐全'}</strong>${v?.depthClears?`<p>深层闭环 ${v.depthClears} 次 · 噩梦 ${v.nightmareClears||0} 次<br>${esc(v.lastRating||'')}</p>`:''}</article>`;}).join('')}</div><article class="final-dossier ${n===5?'unsealed':''}"><div class="eyebrow">${n===5?'EPILOGUE / 总终章已解封':'SEALED / 总终章仍被封存'}</div><h3>让所有人记得</h3><p>${n===5?'五份档案离开了五个封闭地点。被抹去的姓名、转运名单、孩子们的暗号、深海的声纹、黑星的观测记录，第一次出现在同一份公开报告里。城市的广播不再播放安抚指令，而是逐一念出那些真实的名字。你没有消灭记忆里的恐惧，但你让每一个失踪者重新被看见。电话最后响了一次。那一端说：谢谢你还记得。':'在全部五章中，各携带三份证词完成撤离，即可解封最终档案。无时限探索同样计入，不要求速通，也不要求零提示。'}</p></article><div class="btn-row"><button class="btn primary" data-action="close">返回</button><button class="btn ghost" data-campaign="export">导出存档备份</button>${phase==='title'?'<button class="btn ghost" data-campaign="import">导入备份</button>':''}</div>`,'CAMPAIGN / 五处地点，一条证据链',true,'campaign-archive');}
  function walkthrough(){const c=current();openModal(c.name+' · 完整路线',`<div class="journal-list">${c.rooms.map((r,i)=>`<article class="journal-entry"><div class="entry-id">0${i+1} / ${r.name}</div><h3>${r.puzzle.title}</h3><p>${r.puzzle.hints[2]}</p><p>${r.evidence?`本区证词：${r.evidence[0]}。`:''}完成后获得${r.reward}。</p></article>`).join('')}<article class="journal-entry"><h3>撤离与总终章</h3><p>在第 1、第 3、第 5 区域各收集一份证词。最后一道机关完成后，检查本章撤离门并确认撤离；五章全部以三份证词撤离后，战役档案解锁总终章。</p></article></div><button class="btn primary wide" data-action="close">关闭攻略</button>`,'SPOILERS / 全部答案',true,'walkthrough');}
  function exportSave(){if(phase==='playing')saveGame();const blob=new Blob([JSON.stringify(profile,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='silent-ward-campaign-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('存档备份已导出。可在章节菜单的战役档案中导入。');}
  window.Campaign={get selected(){return selected;},get profile(){return profile;},chapters,puzzles,current,roomIds,prepare,createState,canEnter,locked,save,clearRun,doneStage,seen,inspect,finish,walkthrough,select,refreshMenu,initial,isCorrect,flip,archive,check,intro:()=>`${current().name}：先检查${current().rooms[0].name}中的记录。`,restoreBackup(data){if(phase!=='title')throw Error('请先返回章节菜单');if(data?.version!==3||!data.runs||!data.records)throw Error('无效备份');const next={version:3,migratedV2:true,selected:byId[data.selected]?data.selected:'hospital',runs:{},records:{}};for(const c of chapters){const r=validRun(data.runs[c.id],c);if(r)next.runs[c.id]=r;const rec=data.records[c.id];if(rec&&Number.isFinite(rec.clears)&&Number.isFinite(rec.best)&&rec.clears>0)next.records[c.id]={clears:rec.clears,best:rec.best,evidence:Math.max(0,Math.min(3,rec.evidence||0)),truth:rec.truth===true,depthClears:Math.max(0,Math.floor(Number(rec.depthClears)||0)),nightmareClears:Math.max(0,Math.floor(Number(rec.nightmareClears)||0)),bestDepth:Number.isFinite(rec.bestDepth)?rec.bestDepth:null,lastDifficulty:['classic','abyss','nightmare'].includes(rec.lastDifficulty)?rec.lastDifficulty:'classic',lastSeed:window.DepthModel?.cleanSeed(rec.lastSeed)||'',lastRating:typeof rec.lastRating==='string'?rec.lastRating.slice(0,80):''};}profile=next;try{localStorage.removeItem(STORAGE);}catch{}select(next.selected);toast('已恢复通过校验的章节记录。');}};
  document.addEventListener('click',e=>{const pcButton=e.target.closest('[data-pc]');if(pcButton){e.preventDefault();puzzleAction(pcButton);return;}const b=e.target.closest('[data-campaign]');if(!b)return;const a=b.dataset.campaign;if(a==='select')select(b.dataset.chapter);if(a==='archive')archive();if(a==='next'){returnTitle();select(b.dataset.chapter||selected);}if(a==='export')exportSave();if(a==='import')$('#campaignImport').click();if(a==='import-confirm'&&importData){try{Campaign.restoreBackup(importData);closeModal(true);importData=null;}catch(err){toast(err.message);}}});
  document.addEventListener('submit',e=>{if(e.target.id==='campaignPuzzleForm'){e.preventDefault();check();}});
  document.addEventListener('input',e=>{if(e.target.id==='campaignCode'){const p=puzzles.get(activePuzzle),v=puzzleState(p);e.target.value=e.target.value.replace(p.alphabet?/[^a-z]/gi:/[^0-9]/g,'').toUpperCase().slice(0,p.length);v.text=e.target.value;saveGame();}});
  window.addEventListener('ward:scene',()=>{if(phase==='playing')document.documentElement.style.setProperty('--chapter-accent',current().color);});
  const originalReturn=returnTitle;returnTitle=function(){originalReturn();select(state?.chapter||selected);};Ward.returnTitle=returnTitle;
  const upload=document.createElement('input');upload.type='file';upload.id='campaignImport';upload.accept='.json,application/json';upload.hidden=true;document.body.append(upload);
  upload.addEventListener('change',async()=>{const f=upload.files?.[0];if(!f)return;try{if(f.size>1024*1024)throw Error('备份文件过大。请选择本游戏导出的 JSON 文件。');const data=JSON.parse(await f.text());if(data?.version!==3||!data.runs||!data.records)throw Error('不是有效的战役备份。');importData=data;openModal('替换当前战役档案？','<p>导入会替换本浏览器中的全部章节存档和战役记录。建议先导出当前记录留作备份。</p><div class="btn-row"><button class="btn ghost" data-action="close">取消</button><button class="btn primary" data-campaign="import-confirm">确认导入并替换</button></div>','BACKUP / 恢复确认');}catch(err){toast(err.message||'备份无法读取');}finally{upload.value='';}});
  activate(selected);saved=profile.runs[selected]?clone(profile.runs[selected]):null;refreshMenu();persist();
})();
